trigger: none   # Azure Repos trigger disable

resources:
  repositories:
  - repository: k8s-cluster
    type: github
    name: sujeetkushwaha14/k8s-cluster
    endpoint: gitk8s
    trigger:
      branches:
        include:
        - main
        - feature/*

pool:
  name: agent pool local

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: BuildJob
    displayName: 'Build and Test on Self-Hosted Agent'
    steps:
    - checkout: k8s-cluster
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'infra'
        backendServiceArm: 'sanatsp'
        backendAzureRmStorageAccountName: 'stgbacksk123'
        backendAzureRmContainerName: 'contnsbackends'
        backendAzureRmKey: 'terraform.tfstate'
