trigger: none   # Normal push/PR se trigger off

pr: none        # PR trigger bhi off

# GitHub webhook ke naam se service connection use karna
resources:
  webhooks:
    - webhook: gitk8shook   # incoming webhook ka naam
      connection: gitk8shook

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: BuildJob
        displayName: "Build and Test"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - script: echo "Webhook gitk8shook se pipeline trigger ho gaya!"
            displayName: "Verify Webhook Trigger"


# pool:
#   name: agent pool local

# stages:
# - stage: Build
#   displayName: 'Build and Test'
#   jobs:
#   - job: BuildJob
#     displayName: 'Build and Test on Self-Hosted Agent'
#     steps:
#     - checkout: k8s-cluster
#     - task: TerraformInstaller@1
#       inputs:
#         terraformVersion: 'latest'
#     - task: TerraformTask@5
#       inputs:
#         provider: 'azurerm'
#         command: 'init'
#         workingDirectory: 'infra'
#         backendServiceArm: 'sanatsp'
#         backendAzureRmStorageAccountName: 'stgbacksk123'
#         backendAzureRmContainerName: 'contnsbackends'
#         backendAzureRmKey: 'terraform.tfstate'
